In [1]:
import pandas as pd
import numpy as np

In [4]:
dict1 = { "name" : ["Roshan" , "Rohan" , "Rajesh" , "Raju"],
        "Marks" : [34, 56, 78, 89],
          "City" : ["Ambernath" , "Ulhasnagar", "Mumbai" , "Kurla" ]
        }

In [5]:
df = pd.DataFrame(dict1)

In [6]:
df

     name  Marks        City
0  Roshan     34   Ambernath
1   Rohan     56  Ulhasnagar
2  Rajesh     78      Mumbai
3    Raju     89       Kurla

In [8]:
df.describe()  # takes numeric column and gives all math results

           Marks
count   4.000000
mean   64.250000
std    24.390914
min    34.000000
25%    50.500000
50%    67.000000
75%    80.750000
max    89.000000

In [11]:
df.to_csv("Marks_Data", index = False) # this creates a excel file without index = serial no columns

In [12]:
df

     name  Marks        City
0  Roshan     34   Ambernath
1   Rohan     56  Ulhasnagar
2  Rajesh     78      Mumbai
3    Raju     89       Kurla

In [13]:
df.Marks

0    34
1    56
2    78
3    89
Name: Marks, dtype: int64

In [25]:
df["Marks"] [1] = 45

C:\Users\rosha\AppData\Local\Temp\ipykernel_22864\3812731267.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df["Marks"] [1] = 45

In [26]:
df.index = [1,2,3,4]  # index changed

In [27]:
df

     name  Marks        City
1  Roshan     34   Ambernath
2   Rohan     56  Ulhasnagar
3  Rajesh     78      Mumbai
4    Raju     89       Kurla

In [29]:
df.T  # transpose like a matrix

               1           2       3      4
name      Roshan       Rohan  Rajesh   Raju
Marks         34          56      78     89
City   Ambernath  Ulhasnagar  Mumbai  Kurla

In [32]:
type(df)

pandas.DataFrame

In [35]:
df.sort_values(by="Marks")

     name  Marks        City
1  Roshan     34   Ambernath
2   Rohan     56  Ulhasnagar
3  Rajesh     78      Mumbai
4    Raju     89       Kurla

In [46]:
df.loc["City", 0] = None

In [47]:
df

        name  Marks        City     0
1     Roshan   34.0   Ambernath   NaN
2      Rohan   56.0  Ulhasnagar   NaN
3     Rajesh   78.0      Mumbai   NaN
4       Raju   89.0       Kurla   NaN
0        NaN    NaN         NaN   NaN
City     NaN    NaN         NaN  None

In [48]:
df.drop(0)

        name  Marks        City     0
1     Roshan   34.0   Ambernath   NaN
2      Rohan   56.0  Ulhasnagar   NaN
3     Rajesh   78.0      Mumbai   NaN
4       Raju   89.0       Kurla   NaN
City     NaN    NaN         NaN  None

In [52]:
df = df.drop("City")

In [53]:
df

     name  Marks        City    0
1  Roshan   34.0   Ambernath  NaN
2   Rohan   56.0  Ulhasnagar  NaN
3  Rajesh   78.0      Mumbai  NaN
4    Raju   89.0       Kurla  NaN
0     NaN    NaN         NaN  NaN

In [54]:
df = df.drop(0)

In [55]:
df

     name  Marks        City    0
1  Roshan   34.0   Ambernath  NaN
2   Rohan   56.0  Ulhasnagar  NaN
3  Rajesh   78.0      Mumbai  NaN
4    Raju   89.0       Kurla  NaN

In [59]:
df = df.drop(0, axis = 1)

In [60]:
df

     name  Marks        City
1  Roshan   34.0   Ambernath
2   Rohan   56.0  Ulhasnagar
3  Rajesh   78.0      Mumbai
4    Raju   89.0       Kurla

In [65]:
df.loc[[1], :]

     name  Marks       City
1  Roshan   34.0  Ambernath

In [68]:
df.loc[:,["name","Marks"]]

     name  Marks
1  Roshan   34.0
2   Rohan   56.0
3  Rajesh   78.0
4    Raju   89.0

In [75]:
df.loc[(df["Marks"] < 60) & (df["City"] == "Ambernath")]

     name  Marks       City
1  Roshan   34.0  Ambernath

In [76]:
df

     name  Marks        City
1  Roshan   34.0   Ambernath
2   Rohan   56.0  Ulhasnagar
3  Rajesh   78.0      Mumbai
4    Raju   89.0       Kurla

In [81]:
df.iloc[[1,2], [1,2]]  # iloc only accepts integers in it and so to show only first 2 rows nnmks n city

   Marks        City
2   56.0  Ulhasnagar
3   78.0      Mumbai

In [82]:
df # here originla is not changed

     name  Marks        City
1  Roshan   34.0   Ambernath
2   Rohan   56.0  Ulhasnagar
3  Rajesh   78.0      Mumbai
4    Raju   89.0       Kurla

In [83]:
df.drop(1)  # here also original is intact

     name  Marks        City
2   Rohan   56.0  Ulhasnagar
3  Rajesh   78.0      Mumbai
4    Raju   89.0       Kurla

In [87]:
df.drop(["name"],axis = 1, inplace = True)  # here inplace means make changes overall so full df will change

In [88]:
df

   Marks        City
1   34.0   Ambernath
2   56.0  Ulhasnagar
3   78.0      Mumbai
4   89.0       Kurla

In [89]:
df.drop(1)

   Marks        City
2   56.0  Ulhasnagar
3   78.0      Mumbai
4   89.0       Kurla

In [92]:
# now if we have to reset the index 
df.reset_index(drop = True, inplace = True)

In [93]:
df

   Marks        City
0   34.0   Ambernath
1   56.0  Ulhasnagar
2   78.0      Mumbai
3   89.0       Kurla

In [101]:
Student_Data = { "Roll_no" : [1,2,3,4,5],
        "Marks" : [34, 56, 78, 89,90],
          "Pin_Code" : [100,200,300,400,500 ]
        }

In [103]:
newdf = pd.DataFrame(Student_Data)

In [104]:
newdf.count()

Roll_no     5
Marks       5
Pin_Code    5
dtype: int64

In [105]:
newdf.corr()

           Roll_no     Marks  Pin_Code
Roll_no   1.000000  0.952958  1.000000
Marks     0.952958  1.000000  0.952958
Pin_Code  1.000000  0.952958  1.000000

In [106]:
newdf.std()

Roll_no       1.581139
Marks        24.058263
Pin_Code    158.113883
dtype: float64

In [107]:
newdf.sum()

Roll_no       15
Marks        347
Pin_Code    1500
dtype: int64

In [108]:
newdf.describe()

        Roll_no      Marks    Pin_Code
count  5.000000   5.000000    5.000000
mean   3.000000  69.400000  300.000000
std    1.581139  24.058263  158.113883
min    1.000000  34.000000  100.000000
25%    2.000000  56.000000  200.000000
50%    3.000000  78.000000  300.000000
75%    4.000000  89.000000  400.000000
max    5.000000  90.000000  500.000000

In [109]:
newdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Roll_no   5 non-null      int64
 1   Marks     5 non-null      int64
 2   Pin_Code  5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [110]:
newdf.max()

Roll_no       5
Marks        90
Pin_Code    500
dtype: int64

In [111]:
newdf.min()

Roll_no       1
Marks        34
Pin_Code    100
dtype: int64

In [115]:
newdf.median()

Roll_no       3.0
Marks        78.0
Pin_Code    300.0
dtype: float64

In [119]:
data = pd.read_excel("Marks_Data.xlsx")

In [120]:
data

     Name  Marks        City
0  Roshan     88   Ambernath
1   Rohan     56  Ulhasnagar
2  Rajesh     78      Kalyan
3    Raju     88      Mumbra
4   Suman     55        Diva

In [121]:
data.iloc[0,1] = 92

In [122]:
data.to_excel("Marks_Data.xlsx")

In [123]:
data

     Name  Marks        City
0  Roshan     92   Ambernath
1   Rohan     56  Ulhasnagar
2  Rajesh     78      Kalyan
3    Raju     88      Mumbra
4   Suman     55        Diva